/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package loja;

import javax.swing.JOptionPane;

/**
 *
 * @author 20171024110004
 */
public class CadProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadProduto
     */
    public CadProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoLocal = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cxVarejo = new javax.swing.JCheckBox();
        cxAtacado = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        radioSite = new javax.swing.JRadioButton();
        radioLoja = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        campoNome.setToolTipText("Nome completo do produto, sem abreviar.");

        jLabel2.setText("Tipo de Venda");

        cxVarejo.setText("Varejo");
        cxVarejo.setToolTipText("Para vendas a partir de 1 unidade. Consumidor final.");
        cxVarejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxVarejoActionPerformed(evt);
            }
        });

        cxAtacado.setText("Atacado");
        cxAtacado.setToolTipText("Para vendas de caixas fechadas. Cliente cadastrado.");

        jLabel3.setText("Local da Venda:");

        grupoLocal.add(radioSite);
        radioSite.setText("Site");
        radioSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiteActionPerformed(evt);
            }
        });

        grupoLocal.add(radioLoja);
        radioLoja.setText("Loja");

        jLabel4.setText("Categoria:");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Roupas", "Calçados", "Acessórios", "Papelaria", "Maquiagem", "Brinquedos", "Alimentos", "Bebidas", "Higiene" }));

        jLabel5.setText("Preço:");

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(campoNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(comboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cxVarejo)
                                .addGap(18, 18, 18)
                                .addComponent(cxAtacado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(radioSite)
                                .addGap(18, 18, 18)
                                .addComponent(radioLoja)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(campoPreco))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxVarejo)
                    .addComponent(cxAtacado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radioSite)
                    .addComponent(radioLoja))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxVarejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxVarejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxVarejoActionPerformed

    private void radioSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSiteActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        java.sql.Connection conexao = Conexao.getConexao();
        
        try{
            String comando = "INSERT INTO produto " + "VALUES(null,?,?,?,?,?,?)";
            
            java.sql.PreparedStatement ps = conexao.prepareStatement(comando);
            
            ps.setString(1, campoNome.getText());
            
            if(cxVarejo.isSelected()){
                ps.setInt(2, 1);
            }else{
                ps.setInt(2, 0);
            }
            
            if(cxAtacado.isSelected()){
                ps.setInt(3, 1);
            }else{
                ps.setInt(3, 0);
            }
            
            if(radioSite.isSelected()){
                ps.setString(4, "Site");
            }else{
                ps.setString(4, "Loja");
            }
            
            ps.setString(5, comboCategoria.getSelectedItem().toString());
            
            ps.setString(6, campoPreco.getText());
            
            ps.execute();
            
            JOptionPane.showMessageDialog(this, "Inserido com sucesso!");
            
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "ERRO!\n" + e.getMessage());
            e.printStackTrace();
        }//catch
    }//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadProduto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JCheckBox cxAtacado;
    private javax.swing.JCheckBox cxVarejo;
    private javax.swing.ButtonGroup grupoLocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radioLoja;
    private javax.swing.JRadioButton radioSite;
    // End of variables declaration//GEN-END:variables
}
